package com.shoom.ordersystem.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.table_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Integer tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.waiter_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Integer waiterId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.finish_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Date finishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.isFinished
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private boolean isfinished;

    /**
     * 当前订单总价格
     */
    private BigDecimal totalPrice;

    private List<OrderDetail> orderDetails;

    public boolean isIsfinished() {
        return isfinished;
    }

    public List<OrderDetail> getOrderDetails() {
        return orderDetails;
    }

    public void setOrderDetails(List<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.table_id
     *
     * @return the value of orders.table_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Integer getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.table_id
     *
     * @param tableId the value for orders.table_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setTableId(Integer tableId) {
        this.tableId = tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.waiter_id
     *
     * @return the value of orders.waiter_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Integer getWaiterId() {
        return waiterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.waiter_id
     *
     * @param waiterId the value for orders.waiter_id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setWaiterId(Integer waiterId) {
        this.waiterId = waiterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.finish_time
     *
     * @return the value of orders.finish_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.finish_time
     *
     * @param finishTime the value for orders.finish_time
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.isFinished
     *
     * @return the value of orders.isFinished
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public boolean getIsfinished() {
        return isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.isFinished
     *
     * @param isfinished the value for orders.isFinished
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setIsfinished(boolean isfinished) {
        this.isfinished = isfinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tableId=").append(tableId);
        sb.append(", waiterId=").append(waiterId);
        sb.append(", createTime=").append(createTime);
        sb.append(", finishTime=").append(finishTime);
        sb.append(", isfinished=").append(isfinished);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
