package com.shoom.ordersystem.model;

import java.io.Serializable;

public class TableInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column table_info.available
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private Integer available;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.id
     *
     * @return the value of table_info.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.id
     *
     * @param id the value for table_info.id
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column table_info.available
     *
     * @return the value of table_info.available
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public Integer getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column table_info.available
     *
     * @param available the value for table_info.available
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    public void setAvailable(Integer available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", available=").append(available);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
