package com.shoom.ordersystem.mapper;

import com.shoom.ordersystem.entity.UnfinishedOrder;
import com.shoom.ordersystem.model.Order;

import java.util.List;
import java.util.Map;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insert(Order row);

    public List<UnfinishedOrder> getUnfinishedOrders();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insertSelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    Order selectByPrimaryKey(Integer id);


    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKeySelective(Order row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKey(Order row);

    List<Order> getOrdersByWaiterId(int waiterId);

    List<Order> getOrdersByWaiterIdAndIsFinished(Map<String,Integer> param);
}
