package com.shoom.ordersystem.mapper;

import com.shoom.ordersystem.model.Product;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insert(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insertSelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKeySelective(Product row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKey(Product row);
}
