package com.shoom.ordersystem.mapper;

import com.shoom.ordersystem.model.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insertSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKeySelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKey(Role row);
}
