package com.shoom.ordersystem.mapper;

import com.shoom.ordersystem.model.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insert(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insertSelective(RolePermission row);
}
