package com.shoom.ordersystem.mapper;

import com.shoom.ordersystem.model.TableInfo;

public interface TableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insert(TableInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int insertSelective(TableInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    TableInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKeySelective(TableInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table table_info
     *
     * @mbg.generated Fri Apr 07 19:38:52 PDT 2023
     */
    int updateByPrimaryKey(TableInfo row);
}
